# Project configuration for Clippy Rust code linter.
# See full lints list at:
# https://rust-lang.github.io/rust-clippy/master/index.html

# Minimum Supported Rust Version (conservative for WASM tooling)
msrv = "1.90"
