[package]
    authors = ["Prince Muel <68931805+princemuel@users.noreply.github.com>"]
    edition = "2024"
    name    = "tts"
    version = "0.1.0"

[lib]
    crate-type = ["cdylib"]

[dependencies]
    napi        = { workspace = true }
    napi-derive = { workspace = true }

[build-dependencies]
    napi-build = "2"
