name = "Samuel Chukwuzube"
handle = "princemuel"
email = "vansomecsam@gmail.com"
role = "Frontend Engineer"
bio = """Short biography text that gives a brief introduction"""
thumbnail = "https://github.com/princemuel.png"
image = "https://github.com/princemuel.png"
location = "ISS, Space"
[links]
    site = "https://princemuel.com/about"
    repo = "https://github.com/princemuel"
    twitter = "https://twitter.com/iamprincemuel"
    mastodon = "https://mastodon.social/@princemuel"
